use-fork = false

[shell]
program = "fish"
args = ["--login"]

[navigation]
mode = "bookmark"
clickable = false
hide-if-single = true
use-current-path = true
color-automation = []

[fonts]
size = 18
features = []
use-drawable-chars = true
symbol-map = []
disable-warnings-not-found = false
additional-dirs = []

[fonts.regular]
family = "CaskaydiaCove Nerd Font"
style = "Normal"
width = "Normal"
weight = 400

[fonts.bold]
family = "CaskaydiaCove Nerd Font"
style = "Normal"
width = "Normal"
weight = 800

[fonts.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"
width = "Normal"
weight = 400

[fonts.bold-italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"
width = "Normal"
weight = 800

[colors]
background = '#20111b'
foreground = '#968c83'
selection-background = '#45373c'
selection-foreground = '#968c83'
cursor = '#968c83'
black = '#20111b'
red = '#be100e'
green = '#858162'
yellow = '#eaa549'
blue = '#426a79'
magenta = '#97522c'
cyan = '#989a9c'
white = '#968c83'
light_black = '#5e5252'
light_red = '#be100e'
light_green = '#858162'
light_yellow = '#eaa549'
light_blue = '#426a79'
light_magenta = '#97522c'
light_cyan = '#989a9c'
light_white = '#d5ccba'
